# Generated by Django 6.0.4 on 2026-07-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerapplication',
            name='cgp_consent',
            field=models.BooleanField(default=False, verbose_name='Acceptation conditions de partenariat'),
        ),
        migrations.AddField(
            model_name='partnerapplication',
            name='company_size',
            field=models.CharField(blank=True, max_length=40, verbose_name="Taille de l'entreprise"),
        ),
        migrations.AddField(
            model_name='partnerapplication',
            name='job_title',
            field=models.CharField(blank=True, max_length=180, verbose_name='Fonction'),
        ),
        migrations.AddField(
            model_name='partnerapplication',
            name='partner_type',
            field=models.CharField(blank=True, max_length=40, verbose_name='Type de partenariat'),
        ),
        migrations.AddField(
            model_name='partnerapplication',
            name='rgpd_consent',
            field=models.BooleanField(default=False, verbose_name='Consentement RGPD'),
        ),
        migrations.AddField(
            model_name='partnerapplication',
            name='sector',
            field=models.CharField(blank=True, max_length=140, verbose_name="Secteur d'activité"),
        ),
        migrations.AddField(
            model_name='partnerapplication',
            name='services',
            field=models.TextField(blank=True, verbose_name='Services souhaités'),
        ),
        migrations.CreateModel(
            name='PartnerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('file', models.FileField(upload_to='partners/', verbose_name='Fichier')),
                ('document_type', models.CharField(blank=True, max_length=40, verbose_name='Type de document')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Nom original')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Taille (bytes)')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='Type MIME')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='website.partnerapplication', verbose_name='Candidature')),
            ],
            options={
                'verbose_name': 'Document partenaire',
                'verbose_name_plural': 'Documents partenaires',
            },
        ),
    ]
